In [3]:
import pandas as pd
import numpy as np

<h2>Manejo de datos faltante</h2>

In [4]:
data = pd.Series(['a', 'b', np.nan, 'c', 'd', np.nan, 'e'])
data

0      a
1      b
2    NaN
3      c
4      d
5    NaN
6      e
dtype: object

In [5]:
data.isna() #muestra si hay datos faltantes

0    False
1    False
2     True
3    False
4    False
5     True
6    False
dtype: bool

<h3>Filtrar datos faltantes </h3>

In [21]:
datos = pd.Series([1, np.nan, 3, 4 , np.nan, 6, 7, np.nan])
datos

0    1.0
1    NaN
2    3.0
3    4.0
4    NaN
5    6.0
6    7.0
7    NaN
dtype: float64

In [22]:
datos.dropna() #elimina los datos faltantes

0    1.0
2    3.0
3    4.0
5    6.0
6    7.0
dtype: float64

In [23]:
datos.notna() #muestra los datos que no son faltantes

0     True
1    False
2     True
3     True
4    False
5     True
6     True
7    False
dtype: bool

In [24]:
datos[datos.notna()] #filtra los datos que no son faltantes

0    1.0
2    3.0
3    4.0
5    6.0
6    7.0
dtype: float64

In [25]:
data = pd.DataFrame([
    [1, 2, 3, 4],
    [5, 6, np.nan, 8],
    [9, 10, 11, 12],
    [np.nan, np.nan, np.nan, np.nan],
])
data

     0     1     2     3
0  1.0   2.0   3.0   4.0
1  5.0   6.0   NaN   8.0
2  9.0  10.0  11.0  12.0
3  NaN   NaN   NaN   NaN

In [26]:
data.dropna() #elimina las filas que tienen datos faltantes

     0     1     2     3
0  1.0   2.0   3.0   4.0
2  9.0  10.0  11.0  12.0

In [27]:
data.dropna(how='all') #elimina las filas que tienen todos los datos faltantes

     0     1     2     3
0  1.0   2.0   3.0   4.0
1  5.0   6.0   NaN   8.0
2  9.0  10.0  11.0  12.0

In [28]:
data[4] = np.nan #agrega una columna con datos faltantes
data

     0     1     2     3   4
0  1.0   2.0   3.0   4.0 NaN
1  5.0   6.0   NaN   8.0 NaN
2  9.0  10.0  11.0  12.0 NaN
3  NaN   NaN   NaN   NaN NaN

In [29]:
data.dropna(axis= 'columns', how='all') #elimina las columnas que tienen todos los datos faltantes

     0     1     2     3
0  1.0   2.0   3.0   4.0
1  5.0   6.0   NaN   8.0
2  9.0  10.0  11.0  12.0
3  NaN   NaN   NaN   NaN

In [30]:
data.fillna(5) #reemplaza los datos faltantes con 5

     0     1     2     3    4
0  1.0   2.0   3.0   4.0  5.0
1  5.0   6.0   5.0   8.0  5.0
2  9.0  10.0  11.0  12.0  5.0
3  5.0   5.0   5.0   5.0  5.0

In [32]:
data.fillna({1:8, 2:100, 3:1000, 4:10000}) #reemplaza los datos faltantes con una lista de valores

     0     1      2       3        4
0  1.0   2.0    3.0     4.0  10000.0
1  5.0   6.0  100.0     8.0  10000.0
2  9.0  10.0   11.0    12.0  10000.0
3  NaN   8.0  100.0  1000.0  10000.0

In [40]:
data = pd.Series([1, 2, np.nan, 4, 5, np.nan, 7]) 
data

0    1.0
1    2.0
2    NaN
3    4.0
4    5.0
5    NaN
6    7.0
dtype: float64

In [34]:
data.mean() #calcula la media de los datos, ignorando los datos faltantes

np.float64(3.8)

In [39]:
data = data.fillna(0) #reemplaza los datos faltantes con 0
data

0    1.0
1    2.0
2    0.0
3    4.0
4    5.0
5    0.0
6    7.0
dtype: float64

In [38]:
data.mean() #calcula la media de los datos, ignorando los datos faltantes

np.float64(2.7142857142857144)

In [41]:
data = data.fillna(data.mean()) #reemplaza los datos faltantes con la media de los datos
data

0    1.0
1    2.0
2    3.8
3    4.0
4    5.0
5    3.8
6    7.0
dtype: float64

In [42]:
data.mean() #calcula la media de los datos, ignorando los datos faltantes

np.float64(3.8000000000000003)

<h3>Transformacion de los datos </h3>

In [61]:
data = pd.DataFrame({
    'col1': [1, 2, 'd', 'd'],
    'col2': ['a', 'b', 'c', 'c']
})
data

  col1 col2
0    1    a
1    2    b
2    d    c
3    d    c

In [62]:
data.duplicated() #muestra si hay filas duplicadas

0    False
1    False
2    False
3     True
dtype: bool

In [63]:
data.drop_duplicates() #elimina las filas duplicadas

  col1 col2
0    1    a
1    2    b
2    d    c

<h3>Joins</h3>

In [64]:
dta1 = pd.DataFrame({
    'key': ['b', 'b', 'a', 'c', 'a', 'a', 'd'], 'data1': range(7)
})
dta2 = pd.DataFrame({
    'key': ['a', 'b', 'c', 'd'], 'data2': range(4)
})

In [65]:
dta1.head() #muestra las primeras filas del dataframe dta1

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4

In [66]:
dta2.head() #muestra las primeras filas del dataframe dta2

  key  data2
0   a      0
1   b      1
2   c      2
3   d      3

In [68]:
pd.merge(dta1, dta2) #realiza un join por defecto, que es un inner join

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   c      3      2
4   a      4      0
5   a      5      0
6   d      6      3

In [69]:
pd.merge(dta1, dta2, on= 'key') #realiza un join por la columna 'key'

  key  data1  data2
0   b      0      1
1   b      1      1
2   a      2      0
3   c      3      2
4   a      4      0
5   a      5      0
6   d      6      3

In [70]:
dta1 = pd.DataFrame({
    'lkey': ['b', 'b', 'a', 'c', 'a', 'a', 'd'], 'data1': range(7)
})
dta2 = pd.DataFrame({
    'rkey': ['a', 'b', 'c', 'd'], 'data2': range(4)
})

In [71]:
dta1

  lkey  data1
0    b      0
1    b      1
2    a      2
3    c      3
4    a      4
5    a      5
6    d      6

In [73]:
dta2

  rkey  data2
0    a      0
1    b      1
2    c      2
3    d      3

In [76]:
pd.merge(dta1, dta2, left_on='lkey', right_on='rkey') #realiza un join por las columnas 'lkey' y 'rkey'

  lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    a      2    a      0
3    c      3    c      2
4    a      4    a      0
5    a      5    a      0
6    d      6    d      3

In [77]:
pd.merge(dta1, dta2, left_on='lkey', right_on='rkey', how='outer') #realiza un join por las columnas 'lkey' y 'rkey', incluyendo todos los datos de ambos dataframes

  lkey  data1 rkey  data2
0    a      2    a      0
1    a      4    a      0
2    a      5    a      0
3    b      0    b      1
4    b      1    b      1
5    c      3    c      2
6    d      6    d      3

In [78]:
pd.merge(dta1, dta2, left_on='lkey', right_on='rkey', how='left') #realiza un join por las columnas 'lkey' y 'rkey', incluyendo todos los datos del dataframe dta1

  lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    a      2    a      0
3    c      3    c      2
4    a      4    a      0
5    a      5    a      0
6    d      6    d      3

In [79]:
pd.merge(dta1, dta2, left_on='lkey', right_on='rkey' , how='right') #realiza un join por las columnas 'lkey' y 'rkey', incluyendo todos los datos del dataframe dta2

  lkey  data1 rkey  data2
0    a      2    a      0
1    a      4    a      0
2    a      5    a      0
3    b      0    b      1
4    b      1    b      1
5    c      3    c      2
6    d      6    d      3

In [80]:
pd.merge(dta1, dta2, left_on='lkey', right_on='rkey' , how='inner') #realiza un join por las columnas 'lkey' y 'rkey', incluyendo solo los datos que coinciden en ambos dataframes

  lkey  data1 rkey  data2
0    b      0    b      1
1    b      1    b      1
2    a      2    a      0
3    c      3    c      2
4    a      4    a      0
5    a      5    a      0
6    d      6    d      3

<h3> Merge usando indices</h3>

In [81]:
dta1 = pd.DataFrame({
    'key': ['b', 'b', 'a', 'c', 'a', 'a', 'd'], 'data1': range(7)
})
dta2 = pd.DataFrame({
    'group_val': [5, 6.7]
}, index = ['a', 'b']) #asigna los indices 'a' y 'b' a las filas del dataframe dta2

In [82]:
dta1.head() #muestra las primeras filas del dataframe dta1

  key  data1
0   b      0
1   b      1
2   a      2
3   c      3
4   a      4

In [83]:
dta2.head

<bound method NDFrame.head of    group_val
a        5.0
b        6.7>

In [85]:
pd.merge(dta1, dta2, left_on='key', right_index=True) #realiza un join usando la columna 'key' del dataframe dta1 y el indice del dataframe dta2

  key  data1  group_val
0   b      0        6.7
1   b      1        6.7
2   a      2        5.0
4   a      4        5.0
5   a      5        5.0

In [ ]:
pd.merge(dta1, dta2, left_on='key', right_index=True, how='outer') #realiza un join por las columnas 'key'  incluyendo todos los datos de ambos dataframes y muestra de dónde proviene cada fila

  key  data1  group_val
2   a      2        5.0
4   a      4        5.0
5   a      5        5.0
0   b      0        6.7
1   b      1        6.7
3   c      3        NaN
6   d      6        NaN

In [ ]:
pd.merge(dta1, dta2, left_on='key')