PANDAS
Libreria de Python especializada en la manipulacion y analisis de datos

In [14]:
import pandas as pd

Estructura de datos

Series

In [15]:
obj = pd.Series([1, 2, 3, 4, 5]) # creamos un objeto de tipo Series con una lista de numeros
obj # nos muestra el objeto creado con sus indices y valores

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [16]:
obj.array # nos muestra el objeto como un array de numpy

<NumpyExtensionArray>
[np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5)]
Length: 5, dtype: int64

In [17]:
obj.index # nos muestra los indices del objeto

RangeIndex(start=0, stop=5, step=1)

In [18]:
obj2 = pd.Series([1, 2, 3, 4, 5], index=['a', 'b', 'c', 'd', 'e']) # creamos un objeto de tipo Series con una lista de numeros y un indice personalizado
obj2 # nos muestra el objeto creado con sus indices y valores personalizados

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [19]:
obj2.index # nos muestra los indices del objeto personalizado

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [20]:
obj2 = pd.Series([1, 2, 3, 4, 5], index=['primera', 'segundo', 'tercero', 'cuarto', 'quinto']) # creamos un objeto de tipo Series con una lista de numeros y un indice personalizado
obj2 # nos muestra el objeto creado con sus indices y valores personalizados

primera    1
segundo    2
tercero    3
cuarto     4
quinto     5
dtype: int64

In [21]:
obj2.index # nos muestra los indices del objeto personalizado

Index(['primera', 'segundo', 'tercero', 'cuarto', 'quinto'], dtype='object')

In [22]:
obj2['quinto'] # accedemos al valor del indice 'quinto'

np.int64(5)

In [23]:
obj2['cuarto']= 30 # agregamos al indice un nuevo valor al objeto
obj2 # nos muestra el objeto actualizado con el nuevo indice y valor

primera     1
segundo     2
tercero     3
cuarto     30
quinto      5
dtype: int64

In [24]:
obj2[['primera', 'cuarto']] # accedemos a los valores de los indices 'primera' y 'cuarto'

primera     1
cuarto     30
dtype: int64

In [25]:
obj2[obj2 > 3] # accedemos a los valores del objeto que son mayores a 3

cuarto    30
quinto     5
dtype: int64

In [26]:
obj2[obj2< 3] # accedemos a los valores del objeto que son menores a 3

primera    1
segundo    2
dtype: int64

In [27]:
obj2*10 # multiplicamos los valores del objeto por 10

primera     10
segundo     20
tercero     30
cuarto     300
quinto      50
dtype: int64

In [28]:
'segundo' in obj2 # verificamos si el indice 'segundo' esta en el objeto

True

In [29]:
'quinto' in obj2 # verificamos si el indice 'quinto' esta en el objeto

True

In [30]:
'cuarto' in obj2 # verificamos si el indice 'cuarto' esta en el objeto

True

In [31]:
'sexto' in obj2 # verificamos si el indice 'sexto' esta en el objeto

False

Series apartir de un diccionarios

In [32]:
data = {'informatica': 10, 'salud': 32, 'ingenieria': 53, 'humanidades': 74, 'economicas': 95} # creamos un diccionario
data # nos muestra el diccionario creado

{'informatica': 10,
 'salud': 32,
 'ingenieria': 53,
 'humanidades': 74,
 'economicas': 95}

In [33]:
obj3 = pd.Series(data) # creamos un objeto de tipo Series a partir del diccionario
obj3 # nos muestra el objeto creado con sus indices y valores

informatica    10
salud          32
ingenieria     53
humanidades    74
economicas     95
dtype: int64

In [34]:
obj3.to_dict() # convertimos el objeto a un diccionario
obj3

informatica    10
salud          32
ingenieria     53
humanidades    74
economicas     95
dtype: int64

In [35]:
estudiantes = ['informatica', 'ingenieria', 'salud', 'arquitectura', 'economicas'] # creamos una lista de estudiantes
obj4 = pd.Series(data, index=estudiantes) # creamos un objeto de tipo Series a partir de la lista de estudiantes
obj4 # nos muestra el objeto creado con sus indices y valores

informatica     10.0
ingenieria      53.0
salud           32.0
arquitectura     NaN
economicas      95.0
dtype: float64

In [36]:
pd.isna(obj4) # verificamos si el objeto es una Serie de pandas

informatica     False
ingenieria      False
salud           False
arquitectura     True
economicas      False
dtype: bool

In [37]:
pd.notna(obj4) # verificamos si el objeto no es una Serie de pandas

informatica      True
ingenieria       True
salud            True
arquitectura    False
economicas       True
dtype: bool

In [38]:
pd.isna(obj4).sum() # contamos los valores nulos en el objeto

np.int64(1)

In [39]:
pd.notna(obj4).sum() # contamos los valores no nulos en el objeto

np.int64(4)

DATAFRAMES
Una forma de representar y trabajar con datos tabulares.
Diferencia de entre un dataFrame y una serie
El data frama puede manejar tipos de datos mixtos, como numeros, cadenas, booleanos o fechas, mientras que una Serie solo puede manejar un tipo de datos a la vez.

In [40]:
data = {
    'estados': ['Aguascalientes', 'Baja California', 'Baja California Sur', 'Campeche', 'Chiapas'],
    'años': [2020, 2021, 2022, 2023, 2024],
    'poblacion': [1434635, 3769020, 798447, 928363, 554382],
    'superficie': [5616, 71222, 62215, 57000, 55000]
}
data

{'estados': ['Aguascalientes',
  'Baja California',
  'Baja California Sur',
  'Campeche',
  'Chiapas'],
 'años': [2020, 2021, 2022, 2023, 2024],
 'poblacion': [1434635, 3769020, 798447, 928363, 554382],
 'superficie': [5616, 71222, 62215, 57000, 55000]}

In [41]:
frame = pd.DataFrame(data) # creamos un DataFrame a partir del diccionario
frame # nos muestra el DataFrame creado con sus indices y valores

               estados  años  poblacion  superficie
0       Aguascalientes  2020    1434635        5616
1      Baja California  2021    3769020       71222
2  Baja California Sur  2022     798447       62215
3             Campeche  2023     928363       57000
4              Chiapas  2024     554382       55000

In [42]:
frame.head(3) # nos muestra las primeras 3 filas del DataFrame

               estados  años  poblacion  superficie
0       Aguascalientes  2020    1434635        5616
1      Baja California  2021    3769020       71222
2  Baja California Sur  2022     798447       62215

In [43]:
frame.tail(2) # nos muestra las ultimas 2 filas del DataFrame

    estados  años  poblacion  superficie
3  Campeche  2023     928363       57000
4   Chiapas  2024     554382       55000

In [44]:
pd.DataFrame(data, columns=['años', 'estados', 'poblacion','superficie']) # creamos un DataFrame a partir del diccionario y especificamos las columnas

   años              estados  poblacion  superficie
0  2020       Aguascalientes    1434635        5616
1  2021      Baja California    3769020       71222
2  2022  Baja California Sur     798447       62215
3  2023             Campeche     928363       57000
4  2024              Chiapas     554382       55000

In [45]:
frame2 = pd.DataFrame(data, columns=['años', 'estados', 'poblacion','superficie', 'densidad']) # creamos un DataFrame a partir del diccionario y especificamos las columnas, incluyendo una que no existe en el diccionario])
frame2 # nos muestra el DataFrame creado con sus indices y valores, incluyendo la columna 'capital' que tiene valores NaN

   años              estados  poblacion  superficie densidad
0  2020       Aguascalientes    1434635        5616      NaN
1  2021      Baja California    3769020       71222      NaN
2  2022  Baja California Sur     798447       62215      NaN
3  2023             Campeche     928363       57000      NaN
4  2024              Chiapas     554382       55000      NaN

In [46]:
frame2['estados'] # accedemos a la columna 'estados' del DataFrame

0         Aguascalientes
1        Baja California
2    Baja California Sur
3               Campeche
4                Chiapas
Name: estados, dtype: object

In [47]:
frame.estados # accedemos a la columna 'estados' del DataFrame

0         Aguascalientes
1        Baja California
2    Baja California Sur
3               Campeche
4                Chiapas
Name: estados, dtype: object

In [48]:
frame2[['estados', 'años']] # accedemos a las columnas 'estados' y 'años' del DataFrame

               estados  años
0       Aguascalientes  2020
1      Baja California  2021
2  Baja California Sur  2022
3             Campeche  2023
4              Chiapas  2024

In [49]:
frame2['densidad'] = 1000 # agregamos una nueva columna 'densidad' al DataFrame con un valor constante
frame2 # nos muestra el DataFrame actualizado con la nueva columna 'densidad'

   años              estados  poblacion  superficie  densidad
0  2020       Aguascalientes    1434635        5616      1000
1  2021      Baja California    3769020       71222      1000
2  2022  Baja California Sur     798447       62215      1000
3  2023             Campeche     928363       57000      1000
4  2024              Chiapas     554382       55000      1000

In [50]:
frame2['exceso_poblacion'] = frame2['poblacion'] > 3050000 # agregamos una nueva columna 'exceso_poblacion' al DataFrame que indica si la poblacion es mayor a 350000
frame2 # nos muestra el DataFrame actualizado con la nueva columna 'exceso_poblacion

,años,estados,poblacion,superficie,densidad,exceso_poblacion
0,2020,Aguascalientes,1434635,5616,1000,False
1,2021,Baja California,3769020,71222,1000,True
2,2022,Baja California Sur,798447,62215,1000,False
3,2023,Campeche,928363,57000,1000,False
4,2024,Chiapas,554382,55000,1000,False

In [51]:
frame3 = frame2.copy() # creamos una copia del DataFrame
frame3 # nos muestra el DataFrame copiado con sus indices y valores

,años,estados,poblacion,superficie,densidad,exceso_poblacion
0,2020,Aguascalientes,1434635,5616,1000,False
1,2021,Baja California,3769020,71222,1000,True
2,2022,Baja California Sur,798447,62215,1000,False
3,2023,Campeche,928363,57000,1000,False
4,2024,Chiapas,554382,55000,1000,False

In [52]:
frame3 = frame3.drop(index=[1,4]) # eliminamos las filas con indices 1 y 4 del DataFrame copiado
frame3

,años,estados,poblacion,superficie,densidad,exceso_poblacion
0,2020,Aguascalientes,1434635,5616,1000,False
2,2022,Baja California Sur,798447,62215,1000,False
3,2023,Campeche,928363,57000,1000,False

In [53]:
frame3 = frame3.drop(columns=['densidad']) # eliminamos la columna 'densidad' del DataFrame copiado
frame3 # nos muestra el DataFrame copiado sin la columna 'densidad'

   años              estados  poblacion  superficie  exceso_poblacion
0  2020       Aguascalientes    1434635        5616             False
2  2022  Baja California Sur     798447       62215             False
3  2023             Campeche     928363       57000             False

In [54]:
frame3[:2] # accedemos a las primeras 2 filas del DataFrame copiado

   años              estados  poblacion  superficie  exceso_poblacion
0  2020       Aguascalientes    1434635        5616             False
2  2022  Baja California Sur     798447       62215             False

In [55]:
frame3

   años              estados  poblacion  superficie  exceso_poblacion
0  2020       Aguascalientes    1434635        5616             False
2  2022  Baja California Sur     798447       62215             False
3  2023             Campeche     928363       57000             False

In [56]:
frame4 = frame2.copy() # creamos una copia del DataFrame original
frame4 # nos muestra el DataFrame copiado con sus indices y valores

,años,estados,poblacion,superficie,densidad,exceso_poblacion
0,2020,Aguascalientes,1434635,5616,1000,False
1,2021,Baja California,3769020,71222,1000,True
2,2022,Baja California Sur,798447,62215,1000,False
3,2023,Campeche,928363,57000,1000,False
4,2024,Chiapas,554382,55000,1000,False

In [57]:
frame4[2:] # accedemos a las filas desde el indice 2 en adelante del DataFrame copiado

,años,estados,poblacion,superficie,densidad,exceso_poblacion
2,2022,Baja California Sur,798447,62215,1000,False
3,2023,Campeche,928363,57000,1000,False
4,2024,Chiapas,554382,55000,1000,False

In [58]:
frame4[frame4['poblacion'] > 1000000] # accedemos a las filas del DataFrame copiado donde la poblacion es mayor a 1000000

   años          estados  poblacion  superficie  densidad  exceso_poblacion
0  2020   Aguascalientes    1434635        5616      1000             False
1  2021  Baja California    3769020       71222      1000              True

In [59]:
frame4 = frame2.copy() # creamos una copia del DataFrame original
frame4 # nos muestra el DataFrame copiado con sus indices y valores

,años,estados,poblacion,superficie,densidad,exceso_poblacion
0,2020,Aguascalientes,1434635,5616,1000,False
1,2021,Baja California,3769020,71222,1000,True
2,2022,Baja California Sur,798447,62215,1000,False
3,2023,Campeche,928363,57000,1000,False
4,2024,Chiapas,554382,55000,1000,False

In [60]:
indices = ['primera', 'segunda', 'tercera', 'cuarta', 'quinta'] # creamos una lista de indices personalizados
frame4.index = indices # asignamos los indices personalizados al DataFrame copiado
frame4 # nos muestra el DataFrame copiado con los indices personalizados

,años,estados,poblacion,superficie,densidad,exceso_poblacion
primera,2020,Aguascalientes,1434635,5616,1000,False
segunda,2021,Baja California,3769020,71222,1000,True
tercera,2022,Baja California Sur,798447,62215,1000,False
cuarta,2023,Campeche,928363,57000,1000,False
quinta,2024,Chiapas,554382,55000,1000,False

In [61]:
frame2.loc[2] # accedemos a la fila con el indice 'segunda' del DataFrame

años                               2022
estados             Baja California Sur
poblacion                        798447
superficie                        62215
densidad                           1000
exceso_poblacion                  False
Name: 2, dtype: object

In [62]:
frame4.loc['tercera'] # accedemos a la fila con el indice 'tercera' del DataFrame

años                               2022
estados             Baja California Sur
poblacion                        798447
superficie                        62215
densidad                           1000
exceso_poblacion                  False
Name: tercera, dtype: object

In [63]:
frame4.iloc[2] # accedemos a la fila con el indice 2 del DataFrame

años                               2022
estados             Baja California Sur
poblacion                        798447
superficie                        62215
densidad                           1000
exceso_poblacion                  False
Name: tercera, dtype: object

In [69]:
frame3

   años              estados  poblacion  superficie  exceso_poblacion
0  2020       Aguascalientes    1434635        5616             False
2  2022  Baja California Sur     798447       62215             False
3  2023             Campeche     928363       57000             False

In [70]:
frame3.iloc[2] # accedemos a la fila con el indice 2 del DataFrame copiado

años                    2023
estados             Campeche
poblacion             928363
superficie             57000
exceso_poblacion       False
Name: 3, dtype: object

In [71]:
frame3.iloc[[0, 2],[1,3]] # accedemos a las filas con los indices 0 y 2 y las columnas con los indices 1 y 3 del DataFrame copiado

          estados  superficie
0  Aguascalientes        5616
3        Campeche       57000

In [72]:
frame4.loc[['primera', 'tercera'], ['años', 'poblacion']] # accedemos a las filas con los indices 'primera' y 'tercera' y las columnas 'años' y 'poblacion' del DataFrame copiado

         años  poblacion
primera  2020    1434635
tercera  2022     798447

In [73]:
frame4.loc[frame4.poblacion > 1000000, ['años', 'poblacion']] # accedemos a las filas donde la poblacion es mayor a 1000000 y las columnas 'años' y 'poblacion' del DataFrame copiado

         años  poblacion
primera  2020    1434635
segunda  2021    3769020

In [74]:
frame4.describe() # obtenemos un resumen estadístico del DataFrame copiado

              años     poblacion    superficie  densidad
count     5.000000  5.000000e+00      5.000000       5.0
mean   2022.000000  1.496969e+06  50210.600000    1000.0
std       1.581139  1.310135e+06  25706.503084       0.0
min    2020.000000  5.543820e+05   5616.000000    1000.0
25%    2021.000000  7.984470e+05  55000.000000    1000.0
50%    2022.000000  9.283630e+05  57000.000000    1000.0
75%    2023.000000  1.434635e+06  62215.000000    1000.0
max    2024.000000  3.769020e+06  71222.000000    1000.0